AvisFormation.WebUi/AvisFormation.WebUi/Models/AccueilViewModel.cs
using AvisFormation.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AvisFormation.WebUi.Models
{
    public class AccueilViewModel
    {

        public AccueilViewModel()
        {
            ListFormations = new List<FormationAvecAvisDto>();
        }

        public List<FormationAvecAvisDto> ListFormations { get; set; }
    }
}

AvisFormation.WebUi/AvisFormation.WebUi/Controllers/FormationController.cs
using AvisFormation.Data;
using AvisFormation.WebUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvisFormation.WebUi.Controllers
{
    public class FormationController : Controller
    {
        // GET: Formation
        public ActionResult ToutesLesFormations()
        {
            var vm = new AccueilViewModel();
            using (var context = new AvisEntities())
            {
                var listFormation = context.Formation.OrderBy(x => Guid.NewGuid()).ToList();
                foreach (var f in listFormation)
                {
                    var dto = new FormationAvecAvisDto();
                    dto.Formation = f;
                    if (f.Avis.Count == 0)
                        dto.Note = 0;
                    else
                        dto.Note = Math.Round(f.Avis.Average(a => a.Note), 2);
                    vm.ListFormations.Add(dto);
                }
            }
            return View(vm);
        }

        public ActionResult DetailsFormation(string nomSeo)
        {
            var vm = new FormationAvecAvisViewModel();
            using (var context = new AvisEntities())
            {
                var formationEntity = context.Formation.Where(f=>f.NomSeo == nomSeo).FirstOrDefault();
                if (formationEntity == null)
                    return RedirectToAction("Accueil","Home");

                vm.FormationNom = formationEntity.Nom;
                vm.FormationDescription = formationEntity.Description;
                vm.FormationNomSeo = nomSeo;
                vm.FormationUrl = formationEntity.Url;
                if(formationEntity.Avis.Count > 0)
                    vm.Note = formationEntity.Avis.Average(a=>a.Note);
                vm.NombreAvis = formationEntity.Avis.Count;
                vm.Avis = formationEntity.Avis.OrderByDescending(a=>a.DateAvis).ToList();

            }
            return View(vm);
        }

    }

}

AvisFormation.WebUi/AvisFormation.WebUi/Controllers/HomeController.cs
using AvisFormation.Data;
using AvisFormation.WebUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvisFormation.WebUi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Accueil()
        {
            var vm = new AccueilViewModel();
            using (var context = new AvisEntities())
            {
                var listFormation = context.Formation.OrderBy(x => Guid.NewGuid()).Take(4).ToList();
                foreach (var f in listFormation)
                {
                    var dto = new FormationAvecAvisDto();
                    dto.Formation = f;
                    if (f.Avis.Count == 0)
                        dto.Note = 0;
                    else
                        dto.Note = Math.Round(f.Avis.Average(a => a.Note), 2);
                    vm.ListFormations.Add(dto);
                }
            }
            return View(vm);
        }
        [Authorize]
        public ActionResult TestAuthentication()
        {
            return View();
        }

    }
}

AvisFormation.WebUi/AvisFormation.WebUi/Views/Home/Accueil.cshtml
@model AvisFormation.WebUi.Models.AccueilViewModel
@{
    ViewBag.Title = "Accueil";
}
<div class="jumbotron text-center">
    <h1>Avis Formation</h1>
    <p>Choisissez la meilleure formation !</p>
</div>

<div class="container">

    @foreach(var dto in Model.ListFormations)
    {
        <article class="info-block col-md-3 col-sm-6">
            <h4>
                @Html.ActionLink(dto.Formation.Nom,"DetailsFormation","Formation",new {nomSeo=dto.Formation.NomSeo },new {@class="lien-formation" })
            </h4>
            <p>
                @if(dto.Note == 0)
                {
                    <span>Aucun Avis</span>
                }
                else
                {
                    <span class="glyphicon glyphicon-star yellow"></span>
                    if (dto.Note > 1)
                    {
                        <span class="glyphicon glyphicon-star yellow"></span>
                    }
                    if (dto.Note > 2)
                    {
                        <span class="glyphicon glyphicon-star yellow"></span>
                    }
                    if (dto.Note > 3)
                    {
                        <span class="glyphicon glyphicon-star yellow"></span>
                    }
                    if (dto.Note > 4)
                    {
                        <span class="glyphicon glyphicon-star yellow"></span>
                    }

                    <span>@dto.Note / 5</span>
                }
            </p>
            <p>@dto.Formation.Description</p>
        </article>

    }
</div>


<div class="container bg-white text-center padding30">
    <h2>Pourquoi utiliser Avis Formation ?</h2>
    <h3>Bénéfices formateur</h3>

    <div class="row">
        <div class="col-md-6">
            <span class="glyphicon glyphicon-shopping-cart logo-small"></span>
            <h4>Conversion</h4>
            <p>Améliorez votre taux de conversion</p>
        </div>
        <div class="col-md-6">
            <span class="glyphicon glyphicon-fullscreen logo-small" ></span>
            <h4>Visibilité </h4>
            <p>Améliorez votre visibilité</p>
        </div>
        <div class="col-md-6">
            <span class="glyphicon glyphicon-tree-deciduous logo-small" ></span>
            <h4> Fidélisation</h4>
            <p>Obtenez des clients plus fidèles et engagés</p>
        </div>
        <div class="col-md-6">
            <span class="glyphicon glyphicon-heart-empty logo-small" ></span>
            <h4>Confiance</h4>
            <p>Vous bénéficiez des retours d'anciens élèves pour améliorer vos produits</p>
        </div>

    </div>
</div>
<div class="container text-center padding30">
    <div class="row">
        <div class="col-md-8">
            <h3> Professionnels de la formation, affichez notre badge sur votre site pour augmenter vos conversions !</h3>
        </div>
        <div class="col-md-4">
            <div class="widget">
                <div>
                    Avis Elèves 4.8 / 5
                    <span class="glyphicon glyphicon-star yellow"></span><span class="glyphicon glyphicon-star yellow"></span><span class="glyphicon glyphicon-star yellow"></span><span class="glyphicon glyphicon-star yellow"></span><span class="glyphicon glyphicon-star yellow"></span>
                </div>
                <div class="widget-bottom">
                    Avis récoltés par AvisFormation.fr
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container bg-white text-center padding30">
    <div class="row">
        <div class="col-md-3">
            <p class="bigpercent">85%</p>
            <p><b>85% des internautes consultent les avis clients avant d'acheter en ligne</b></p>
        </div>
        <div class="col-md-3">
            <p class="bigpercent">91%</p>
            <p><b>91% de ceux qui lisent les avis les considèrent comme le vecteur numéro 1 dans leur décision d'achat</b></p>
        </div>
        <div class="col-md-3">
            <p class="bigpercent">25%</p>
            <p><b>+25% du taux de conversion pour les sites avec étoiles Google</b></p>

        </div>
        <div class="col-md-3">
            <p class="bigpercent"> 80%</p>
            <p><b>80 % des avis ont une note et un commentaire positifs</b></p>
        </div>
    </div>
</div>

AvisFormation.WebUi/AvisFormation.WebUi/Views/Home/TestAuthentication.cshtml
@{
    ViewBag.Title = "TestAuthentication";
}

<h2>TestAuthentication</h2>


authentication OK