CorrectionPanier/CorrectionPanier/Controllers/CategorieController.cs
using CorrectionPanier.Models;
using CorrectionPanier.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorrectionPanier.Controllers
{
    public class CategorieController : Controller
    {
        // GET: Categorie
        public ActionResult Index()
        {
            InitCategories();
            CategorieIndexVM viewModel = new CategorieIndexVM();
            viewModel.ListeCategories = Categorie.GetCateogries();
            return View(viewModel);
        }

        public ActionResult AddCategorie()
        {
            InitCategories();
            return View();
        }

        [HttpPost]
        public ActionResult AddCategoriePost(Categorie categorie)
        {
            InitCategories();
            if (categorie.Id == 0)
            {
                categorie.Save();
            }
            else
            {
                categorie.Update();
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult EditCategorie(int id)
        {
            InitCategories();
            EditCategorieVM viewModel = new EditCategorieVM();
            viewModel.categorie = Categorie.GetCategorieById(id);
            return View(viewModel);
        }
        private void InitCategories()
        {
            ViewBag.categories = Categorie.GetCateogries();
        }
    }
}

CorrectionPanier/CorrectionPanier/Controllers/ProduitController.cs
using CorrectionPanier.Models;
using CorrectionPanier.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorrectionPanier.Controllers
{
    public class ProduitController : Controller
    {
        // GET: Produit
        public ActionResult Index()
        {
            InitCategories();
            ProduitIndexVM viewModel = new ProduitIndexVM();
            viewModel.ListeProduits = Produit.GetProduits();
            return View(viewModel);
        }
        public ActionResult GetByCategorie(int id)
        {
            InitCategories();
            ProduitIndexVM viewModel = new ProduitIndexVM();
            viewModel.ListeProduits = Produit.GetProduitByCategorie(id);
            return View("Index",viewModel);
        }

        public ActionResult AddProduit()
        {
            InitCategories();
            AddProduitVM viewModel = new AddProduitVM();
            viewModel.ListeCateogries = Categorie.GetCateogries(); 
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddProduitPost([Bind(Include ="Libelle, Prix")]Produit produit, int categorie)
        {
            InitCategories();
            produit.Categorie = Categorie.GetCategorieById(categorie);
            produit.Save();
            return RedirectToAction("Index");
        }

        private void InitCategories()
        {
            ViewBag.categories = Categorie.GetCateogries();
        }

        public ActionResult AddPanier(int id)
        {
            Produit p = Produit.GetProduitById(id);
            HttpCookie cookie = Request.Cookies["panier"];
            if(cookie == null)
            {
                cookie = new HttpCookie("panier");
                List<Produit> produitPanier = new List<Produit>();
                produitPanier.Add(p);
                cookie["listeproduits"] = JsonConvert.SerializeObject(produitPanier);
            }
            else
            {
                List<Produit> produitPanier = JsonConvert.DeserializeObject<List<Produit>>(cookie["listeproduits"]);
                produitPanier.Add(p);
                cookie["listeproduits"] = JsonConvert.SerializeObject(produitPanier);
            }
            Response.Cookies.Add(cookie);
            return RedirectToAction("Panier");
        }

        public ActionResult Panier()
        {
            InitCategories();
            PanierVM viewModel = new PanierVM();
            HttpCookie cookie = Request.Cookies["panier"];
            if (cookie != null)
            {
                viewModel.ListeProduits = JsonConvert.DeserializeObject<List<Produit>>(cookie["listeproduits"]);
                viewModel.Total = Models.Panier.CalculeTotal(viewModel.ListeProduits);
            }
            return View(viewModel);
        }
    }
}

CorrectionPanier/CorrectionPanier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon e-commerce</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ecommerce", "Index", "Produit", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Produit")</li>
                    <li>@Html.ActionLink("Ajouter une categorie", "AddCategorie", "Categorie")</li>
                    <li>@Html.ActionLink("Ajouter un produit", "AddProduit", "Produit")</li>
                    <li>@Html.ActionLink("Panier","Panier","Produit")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-lg-3">
                <ul class="MenuLeft">
                    @foreach (var categorie in ViewBag.categories as List<CorrectionPanier.Models.Categorie>)
                    {
                        <li>@Html.ActionLink(categorie.Label, "GetByCategorie", "Produit",new { id = categorie.Id},null)</li>
                    }
                </ul>
            </div>
            <div class="col-lg-9">
                @RenderBody()
            </div>
        </div>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Formation AFPA</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>